# These rules apply to the Nitro Umbrella app and all components.

require:
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'spec/*'
    - 'spec/**/*'
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'config/**'
    - 'config/**/*'
    - 'bin/**'

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: false

Lint/ScriptPermission:
  Enabled: false

Lint/StructNewOverride:
  Enabled: true

Metrics/BlockLength:
  Enabled: false

Naming/FileName:
  Exclude:
    - 'Guardfile'
    - 'Capfile'

Naming/MethodParameterName:
  AllowedNames:
    - io
    - id
    - to
    - by
    - 'on'
    - in
    - at

Style/Documentation:
  Enabled: false

Style/ExponentialNotation:
  Enabled: false

# This is enabled in Nitro, and important to enforce to prepare for Ruby 3.0.
# But Ruby will not be raised to 3.0 during the duration of the PCA.
# So disabling this rule dramatically reduces noise.
Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Style/RescueStandardError:
  EnforcedStyle: implicit

# Single quotes being faster is hardly measurable and only affects parse time.
# Enforcing double quotes reduces the times where you need to change them when introducing an interpolation.
# Use single quotes only if their semantics are needed.
Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

## Ignore some Metrics violations

Metrics/BlockNesting:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

## Ignore cops that raise on design features for the project

Security/Open:
  Enabled: false

Style/ClassVars:
  Enabled: false